# Generated by Django 3.2.9 on 2021-11-03 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=30, verbose_name='Nombre del producto')),
                ('stockInicial', models.IntegerField(verbose_name='Stock inicial')),
                ('stockActual', models.IntegerField(verbose_name='Stock Actual')),
                ('precio', models.IntegerField(verbose_name='precio del producto')),
                ('estado', models.BooleanField(verbose_name='estado del producto')),
                ('createDate', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('updateDate', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
